/* SanaVerse – generated by scripts/bundle.mjs from src/*.js. Edit the files in src/, then re-run the bundler. */
(function () {
'use strict';

/* ===== storage.js ===== */
/* SanaVerse – on-device storage. Text + audio in IndexedDB; progress, bookmarks, settings in localStorage. Nothing leaves the device. */
const LS = {
  get(k, d) { try { const v = localStorage.getItem(k); return v == null ? d : JSON.parse(v); } catch { return d; } },
  set(k, v) { try { localStorage.setItem(k, JSON.stringify(v)); return true; } catch { return false; } },
  del(k) { try { localStorage.removeItem(k); } catch {} }
};
const S = Object.assign({ theme: 'auto', rate: 1, size: 19, quality: 'natural', nvoice: 'af_heart', bvoice: '', cap: 500 }, LS.get('sv:settings', {}));
if (S.voice && !S.bvoice) { S.bvoice = S.voice; delete S.voice; } // settings from the first (browser-voice-only) version
const saveS = () => LS.set('sv:settings', S);

const STORES = ['meta', 'text', 'audio', 'ai'];
const DB = {
  open() {
    return this.p || (this.p = new Promise((ok, no) => {
      const r = indexedDB.open('sanaverse', 2);
      r.onupgradeneeded = () => {
        const db = r.result;
        ['meta', 'text'].forEach(n => db.objectStoreNames.contains(n) || db.createObjectStore(n, { keyPath: 'id' }));
        ['audio', 'ai'].forEach(n => db.objectStoreNames.contains(n) || db.createObjectStore(n, { keyPath: 'key' }));
      };
      r.onsuccess = () => ok(r.result); r.onerror = () => no(r.error);
    }));
  },
  async run(names, mode, fn) {
    const db = await this.open();
    return new Promise((ok, no) => {
      const t = db.transaction(names, mode); const out = fn(...names.map(n => t.objectStore(n)));
      t.oncomplete = () => ok(out && 'result' in out ? out.result : undefined); t.onerror = t.onabort = () => no(t.error);
    });
  },
  metas() { return this.run(['meta'], 'readonly', m => m.getAll()); },
  text(id) { return this.run(['text'], 'readonly', t => t.get(id)); },
  put(meta, text) { return this.run(['meta', 'text'], 'readwrite', (m, t) => { m.put(meta); t.put(text); }); },
  async del(id) { await this.audioClear(id); return this.run(['meta', 'text'], 'readwrite', (m, t) => { m.delete(id); t.delete(id); }); },
  clear() { return this.run(STORES, 'readwrite', (...s) => s.forEach(x => x.clear())); },
  /* generated narration, one record per segment (~1 minute) */
  audioGet(key) { return this.run(['audio'], 'readonly', a => a.get(key)); },
  audioPut(rec, idx) { return this.run(['audio', 'ai'], 'readwrite', (a, i) => { a.put(rec); i.put(idx); }); },
  audioIdx() { return this.run(['ai'], 'readonly', i => i.getAll()); },
  audioDelete(keys) { return this.run(['audio', 'ai'], 'readwrite', (a, i) => keys.forEach(k => { a.delete(k); i.delete(k); })); },
  async audioClear(bookId) {
    if (!bookId) return this.run(['audio', 'ai'], 'readwrite', (a, i) => { a.clear(); i.clear(); });
    const idx = (await this.audioIdx()).filter(x => x.bookId === bookId).map(x => x.key); return idx.length ? this.audioDelete(idx) : undefined;
  }
};


/* ===== extract.js ===== */
/* SanaVerse – PDF text extraction, cleanup, chapter detection and narration prep. Pure logic, no UI. */
const MAXC = 260;          // max characters per chunk
const PDF_CDN = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/';
class AppError extends Error {}
const uid = () => (crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36) + Math.random().toString(36).slice(2));

const CH = /^(chapter|part|book|section)\s+(\d+|[ivxlc]+|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve)\b/i;
const FRONT = /^(prologue|epilogue|preface|foreword|introduction|conclusion|afterword|appendix|acknowledg(e)?ments)\.?$/i;
const isChap = t => t.length < 80 && /^[A-Z0-9]/.test(t) && (CH.test(t) || FRONT.test(t));
const PGNUM = /^\s*(page\s+)?(\d{1,4}|[ivxlc]{1,6})\s*(of\s+\d+)?\s*$/i;
const LIG = { 'ﬁ': 'fi', 'ﬂ': 'fl', 'ﬀ': 'ff', 'ﬃ': 'ffi', 'ﬄ': 'ffl', 'ﬅ': 'st', 'ﬆ': 'st' };

function clean(s) {
  return s.replace(/[ﬁﬂﬀﬃﬄﬅﬆ]/g, c => LIG[c]).replace(/\u00AD/g, '')
    .replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F\u200B\uFEFF]/g, '').replace(/\s+/g, ' ').trim();
}
function pageLines(tc) {
  const lines = []; let cur = null, prevEnd = 0;
  for (const it of tc.items) {
    if (typeof it.str !== 'string') continue;
    const x = it.transform[4], y = it.transform[5], ht = Math.abs(it.height) || Math.abs(it.transform[3]) || 10;
    if (!it.str.trim()) { if (it.hasEOL) cur = null; else if (cur && !cur.t.endsWith(' ')) cur.t += ' '; continue; }
    if (!cur || Math.abs(y - cur.y) > ht * 0.5) { cur = { t: '', y, h: ht }; lines.push(cur); prevEnd = x; }
    else if (x - prevEnd > ht * 0.2 && !cur.t.endsWith(' ') && !it.str.startsWith(' ')) cur.t += ' ';
    cur.t += it.str; cur.h = Math.max(cur.h, ht); prevEnd = x + it.width;
    if (it.hasEOL) cur = null;
  }
  return lines.map(l => ({ ...l, t: clean(l.t) })).filter(l => l.t);
}
let HV = new Set(); // hyphenated words seen mid-line in this book (so real compounds keep their hyphen)
function join(a, b) {
  if (/[a-z]-$/.test(a) && /^[a-z]/.test(b)) {
    const m = /([A-Za-z]+)-$/.exec(a), w = /^[a-z]+/.exec(b)[0];
    return m && HV.has((m[1] + '-' + w).toLowerCase()) ? a + b : a.slice(0, -1) + b;
  }
  return a + ' ' + b;
}

function buildBlocks(pages) {
  const n = pages.length;
  HV = new Set(); pages.forEach(p => p.forEach(l => (l.t.match(/[A-Za-z]+(?:-[A-Za-z]+)+/g) || []).forEach(w => HV.add(w.toLowerCase()))));
  if (n >= 4) { // drop repeated running headers/footers and page numbers (only at page edges)
    const key = t => t.toLowerCase().replace(/\d+/g, '#'), cnt = {}, lim = Math.max(3, n * 0.25);
    const edges = p => [...p.slice(0, 2), ...p.slice(-2)];
    pages.forEach(p => new Set(edges(p).map(l => key(l.t))).forEach(k => cnt[k] = (cnt[k] || 0) + 1));
    pages = pages.map(p => p.filter((l, i) => {
      const e = i < 2 || i >= p.length - 2; if (!e) return true;
      if (PGNUM.test(l.t)) return false;
      const c = cnt[key(l.t)] || 0;
      return !(c >= lim && (!isChap(l.t) || c >= n * 0.5));
    }));
  }
  const hs = pages.flat().map(l => l.h).sort((a, b) => a - b), med = hs[hs.length >> 1] || 10;
  const blocks = [];
  for (const p of pages) {
    let prev = null, para = null;
    for (const l of p) {
      const big = l.h > med * 1.4, mid = l.h > med * 1.2, short = l.t.length < 100;
      const lvl = (isChap(l.t) || (big && short)) ? 2
        : ((mid && short) || (l.t.length < 60 && /[A-Z]{4}/.test(l.t) && l.t === l.t.toUpperCase() && !/[.,;:]$/.test(l.t))) ? 1 : 0;
      if (!prev && blocks.length) { // paragraph continuing from previous page
        const b = blocks[blocks.length - 1];
        if (!b.head && !lvl && !/[.!?:"”’)\]…]$/.test(b.t) && /^[a-z]/.test(l.t)) para = b;
      }
      const gap = prev ? prev.y - l.y : 0;
      const cont = para && ((!lvl && !para.head && gap <= l.h * 1.7) ||
        (lvl && para.head === lvl && Math.abs(para.h - l.h) < 0.5 && !isChap(para.t) && gap <= l.h * 1.7));
      if (cont) para.t = join(para.t, l.t); else { para = { t: l.t, head: lvl, h: l.h }; blocks.push(para); }
      prev = l;
    }
  }
  const out = [];
  for (const b of blocks) {
    const p = out[out.length - 1];
    if (p && p.t === b.t) continue; // exact duplicate
    if (p && p.head && b.head && isChap(p.t) && !isChap(b.t) && p.t.length < 22 && !p.merged) { p.t = p.t.replace(/[.:]$/, '') + ': ' + b.t; p.merged = true; continue; }
    out.push(b);
  }
  return out;
}
const ABBR = /(?:\b(?:Mr|Mrs|Ms|Dr|Prof|Sr|Jr|St|vs|etc|Fig|No|Inc|Ltd|Co|Gen|Col|Capt|Sgt|Rev|Hon)|\b[A-Z]|\be\.g|\bi\.e)\.["”’')\]]*\s*$/;
function splitText(t) {
  const raw = t.match(/[^.!?…]+(?:[.!?…]+["”’')\]]*\s*|$)/g) || [t], s = [];
  for (const x of raw) { if (s.length && ABBR.test(s[s.length - 1])) s[s.length - 1] += x; else s.push(x); }
  const out = []; let cur = '';
  for (let x of s) {
    x = x.trim(); if (!x) continue;
    while (x.length > MAXC + 40) {
      let k = x.lastIndexOf(', ', MAXC); if (k < 80) k = x.lastIndexOf(' ', MAXC); if (k < 1) k = MAXC;
      const part = x.slice(0, k + 1).trim(); x = x.slice(k + 1).trim();
      if (cur) { out.push(cur); cur = ''; } out.push(part);
    }
    if (cur && cur.length + x.length + 1 > MAXC) { out.push(cur); cur = x; } else cur = cur ? cur + ' ' + x : x;
  }
  if (cur) out.push(cur); return out;
}
function structure(blocks) { // → chunks [[text, flag]] flag: 0 continuation, 1 new paragraph, 2 heading; secs [{title,start}]
  const c2 = blocks.filter(b => b.head === 2).length, c1 = blocks.filter(b => b.head >= 1).length;
  const thr = c2 >= 2 ? 2 : (c1 >= 3 ? 1 : 9);
  const chunks = [], secs = []; let secChars = 0;
  const startSec = t => { secs.push({ title: t, start: chunks.length }); secChars = 0; };
  for (const b of blocks) {
    if (b.head >= thr) { startSec(b.t.slice(0, 90)); chunks.push([b.t, 2]); continue; }
    if (!secs.length) startSec(thr === 9 ? 'Section 1' : 'Opening');
    if (thr === 9 && secChars > 8000) startSec('Section ' + (secs.length + 1));
    let first = 1; for (const c of splitText(b.t)) { chunks.push([c, first]); first = 0; secChars += c.length; }
  }
  return { chunks, secs };
}


/* ---------- narration prep: what the voice actually reads (the on-screen text stays untouched) ---------- */
const ROMAN = { i: 1, v: 5, x: 10, l: 50, c: 100 };
const roman = r => { let n = 0; r = r.toLowerCase(); for (let i = 0; i < r.length; i++) { const v = ROMAN[r[i]], nx = ROMAN[r[i + 1]] || 0; n += v < nx ? -v : v; } return n; };
const ABBREV = [[/\bMr\./g, 'Mister'], [/\bMrs\./g, 'Missus'], [/\bDr\./g, 'Doctor'], [/\bProf\./g, 'Professor'], [/\bvs\./gi, 'versus'], [/\betc\./g, 'et cetera'], [/\be\.g\./gi, 'for example'], [/\bi\.e\./gi, 'that is'], [/\bSt\.(?=\s+[A-Z])/g, 'Saint'], [/\bNo\.(?=\s*\d)/g, 'Number']];
function prepSpeech(t, flag) {
  let s = t;
  if (flag === 2) s = s.replace(/^(chapter|part|book|section)\s+([ivxlc]+)\b/i, (m, a, r) => /^[ivxlc]+$/i.test(r) ? a + ' ' + roman(r) : m);
  const L = s.replace(/[^A-Za-z]/g, ''), U = L.replace(/[^A-Z]/g, '');
  if (L.length > (flag === 2 ? 3 : 8) && U.length / L.length > 0.6) s = s.toLowerCase().replace(/(^|[\s"“(])([a-z])/g, (m, a, b) => a + b.toUpperCase()); // SHOUTED HEADINGS → Normal Case
  for (const [re, to] of ABBREV) s = s.replace(re, to);
  return s.replace(/\[\d+(?:[,–-]\s*\d+)*\]/g, '').replace(/https?:\/\/\S+/g, 'link').replace(/&/g, ' and ')
    .replace(/(\d)\s*[–—]\s*(\d)/g, '$1 to $2').replace(/\s*[—–]\s*/g, ', ').replace(/\s+/g, ' ').trim();
}

/* ---------- PDF → { meta, chunks, secs } ---------- */
async function coverImage(pdf) {
  try {
    const pg = await pdf.getPage(1), v0 = pg.getViewport({ scale: 1 }), v = pg.getViewport({ scale: 220 / v0.width });
    const c = document.createElement('canvas'); c.width = Math.round(v.width); c.height = Math.round(v.height);
    await pg.render({ canvasContext: c.getContext('2d'), viewport: v }).promise;
    const u = c.toDataURL('image/jpeg', 0.7); return u.length < 150000 ? u : '';
  } catch { return ''; }
}
const tick = () => new Promise(r => setTimeout(r, 0));
async function extractPdf(file, onProgress) {
  if (!(file.type === 'application/pdf' || /\.pdf$/i.test(file.name))) throw new AppError('That doesn’t look like a PDF. Please choose a .pdf file.');
  if (!file.size) throw new AppError('That file is empty.');
  if (file.size > 300 * 1024 * 1024) throw new AppError('That PDF is very large (over 300 MB). Please try a smaller file.');
  if (!window.pdfjsLib) throw new AppError('The PDF reader could not load. Connect to the internet once, then try again.');
  onProgress('Reading PDF…', 2);
  pdfjsLib.GlobalWorkerOptions.workerSrc = PDF_CDN + 'pdf.worker.min.js';
  const buf = await file.arrayBuffer(); let pdf;
  try { pdf = await pdfjsLib.getDocument({ data: buf, isEvalSupported: false }).promise; }
  catch (e) { throw new AppError(e && e.name === 'PasswordException' ? 'This PDF is password-protected. Remove the password and try again.' : 'This file couldn’t be opened. It may be damaged or not a real PDF.'); }
  const info = await Promise.resolve().then(() => pdf.getMetadata()).then(m => m.info || {}).catch(() => ({}));
  const pages = [];
  for (let n = 1; n <= pdf.numPages; n++) {
    const pg = await pdf.getPage(n); pages.push(pageLines(await pg.getTextContent())); pg.cleanup();
    if (n % 5 === 0 || n === pdf.numPages) { onProgress(`Extracting text… page ${n} of ${pdf.numPages}`, 5 + 75 * n / pdf.numPages); await tick(); }
  }
  onProgress('Cleaning text…', 84); await tick();
  const blocks = buildBlocks(pages), chars = blocks.reduce((a, b) => a + b.t.length, 0);
  if (chars < 200 || chars < pdf.numPages * 25) throw new AppError('This PDF appears to contain scanned pages rather than selectable text, so SanaVerse can’t read it aloud. Try a text-based PDF, or run it through an OCR tool first.');
  onProgress('Detecting chapters…', 90); await tick();
  const { chunks, secs } = structure(blocks);
  onProgress('Preparing narration…', 95); const cover = await coverImage(pdf);
  const base = file.name.replace(/\.pdf$/i, '').replace(/_+/g, ' ').trim();
  const meta = { id: uid(), title: clean(info.Title || '') || base || 'Untitled book', author: clean(info.Author || ''), pages: pdf.numPages, chars, cover, created: Date.now() };
  return { meta, text: { id: meta.id, chunks, secs } };
}


/* ===== tts.js ===== */
/* SanaVerse – speech engine wrapper: text → PCM audio. "kokoro" = real neural voice in a worker; "mock" = test double (?engine=mock). */

const SR = 24000;
const VOICES = [['af_heart', 'Heart – US English, female'], ['af_bella', 'Bella – US English, female'], ['af_nicole', 'Nicole – US English, female (soft)'], ['af_sarah', 'Sarah – US English, female'],
  ['am_adam', 'Adam – US English, male'], ['am_michael', 'Michael – US English, male'], ['bf_emma', 'Emma – British English, female'], ['bm_george', 'George – British English, male']];
const Q = new URLSearchParams(location.search);
const MOCK = Q.get('engine') === 'mock', MOCK_SCALE = +(Q.get('scale') || 20), MOCK_DELAY = +(Q.get('delay') || 20);

class Engine {
  constructor() { this.state = 'idle'; this.mb = 0; this.totalMb = 0; this.listeners = []; this.pending = new Map(); this.n = 0; this.files = {}; this.kind = MOCK ? 'mock' : 'kokoro'; }
  get supported() { return MOCK || (typeof Worker !== 'undefined' && typeof WebAssembly !== 'undefined'); }
  get ready() { return this.state === 'ready'; }
  get modelKnown() { return MOCK || LS.get('sv:model', false); }
  on(fn) { this.listeners.push(fn); }
  set(state) { this.state = state; this.listeners.forEach(f => f(this)); }
  ensure() {
    if (this.ready) return Promise.resolve(true);
    if (this.init) return this.init;
    this.init = new Promise(ok => {
      if (MOCK) { this.set('ready'); return ok(true); }
      try { this.w = new Worker('tts-worker.js', { type: 'module' }); } catch { this.error = 'Workers unavailable'; this.set('error'); return ok(false); }
      this.set(this.modelKnown ? 'loading' : 'downloading');
      this.w.onmessage = e => this.msg(e.data, ok);
      this.w.onerror = () => { this.error = 'Voice engine failed to start'; this.set('error'); ok(false); };
      this.w.postMessage({ type: 'init' });
    }).then(r => { if (!r) { this.init = null; try { this.w && this.w.terminate(); } catch {} } return r; });
    return this.init;
  }
  msg(m, ok) {
    if (m.type === 'progress') {
      const p = m.p || {};
      if (p.file && p.total) this.files[p.file] = { l: p.loaded || 0, t: p.total };
      const f = Object.values(this.files), L = f.reduce((a, x) => a + x.l, 0), T = f.reduce((a, x) => a + x.t, 0);
      this.mb = L / 1048576; this.totalMb = T / 1048576; this.set(this.state === 'ready' ? 'ready' : (T && L < T ? 'downloading' : 'loading'));
    } else if (m.type === 'ready') { LS.set('sv:model', true); this.set('ready'); ok(true); }
    else if (m.type === 'error') { this.error = m.msg; this.set('error'); ok(false); }
    else if (m.type === 'audio') { const p = this.pending.get(m.id); p && (this.pending.delete(m.id), p.ok({ pcm: m.pcm, sr: m.sr })); }
    else if (m.type === 'genError') { const p = this.pending.get(m.id); p && (this.pending.delete(m.id), p.no(new Error(m.msg))); }
  }
  generate(text, voice) {
    if (MOCK) return new Promise(ok => setTimeout(() => { // silence-with-a-tone whose length mimics real speech (~15 chars/s, sped up by ?scale)
      const n = Math.max(2400, Math.round(text.length / 15 / MOCK_SCALE * SR)), a = new Float32Array(n);
      for (let i = 0; i < n; i++) a[i] = 0.02 * Math.sin(i * 0.05); ok({ pcm: a, sr: SR }); }, MOCK_DELAY));
    return new Promise((ok, no) => { const id = ++this.n; this.pending.set(id, { ok, no }); this.w.postMessage({ type: 'gen', id, text, voice }); });
  }
  async removeModel() {
    try { this.w && this.w.terminate(); } catch {} this.w = null; this.init = null; this.files = {}; this.pending.clear();
    try { await caches.delete('transformers-cache'); } catch {}
    LS.set('sv:model', false); this.set('idle');
  }
}
const engine = new Engine();

function encodeWav(pcm, sr = SR) { // Float32 mono → 16-bit PCM WAV
  const n = pcm.length, buf = new ArrayBuffer(44 + n * 2), v = new DataView(buf);
  const w = (o, s) => { for (let i = 0; i < s.length; i++) v.setUint8(o + i, s.charCodeAt(i)); };
  w(0, 'RIFF'); v.setUint32(4, 36 + n * 2, true); w(8, 'WAVE'); w(12, 'fmt '); v.setUint32(16, 16, true); v.setUint16(20, 1, true); v.setUint16(22, 1, true);
  v.setUint32(24, sr, true); v.setUint32(28, sr * 2, true); v.setUint16(32, 2, true); v.setUint16(34, 16, true); w(36, 'data'); v.setUint32(40, n * 2, true);
  for (let i = 0; i < n; i++) { const s = Math.max(-1, Math.min(1, pcm[i])); v.setInt16(44 + i * 2, s < 0 ? s * 0x8000 : s * 0x7fff, true); }
  return new Blob([buf], { type: 'audio/wav' });
}
let sil;
const silenceUrl = () => sil || (sil = URL.createObjectURL(encodeWav(new Float32Array(SR / 2), SR))); // keeps the media session alive while narration is being prepared


/* ===== player.js ===== */
/* SanaVerse – audiobook player. Neural mode: narration is generated per ~1-minute segment, cached on-device, and played through a real
   <audio> element + Media Session (lock-screen controls, background playback). Basic mode: device speech synthesis (fallback). */



const SEG_CHARS = 700, AHEAD = 3, AV = 1; // AV = audio cache version (bump if narration prep changes)
const p2 = n => String(n).padStart(2, '0');
function fmt(s) { s = Math.max(0, Math.round(s)); const H = Math.floor(s / 3600), M = Math.floor(s % 3600 / 60), c = s % 60; return H ? `${H}:${p2(M)}:${p2(c)}` : `${M}:${p2(c)}`; }
const concat = (parts, n) => { const o = new Float32Array(n); let p = 0; for (const a of parts) { o.set(a, p); p += a.length; } return o; };

function makeSegs(chunks, secs) { // consecutive chunks grouped into ~1 minute of speech; never crossing a chapter boundary
  const segs = [];
  secs.forEach((s, k) => {
    const end = k + 1 < secs.length ? secs[k + 1].start : chunks.length; let a = s.start, n = 0;
    for (let i = s.start; i < end; i++) {
      n += chunks[i][0].length;
      if (n >= SEG_CHARS || i === end - 1) {
        if (i === end - 1 && n < 250 && segs.length && segs[segs.length - 1].s === k) segs[segs.length - 1].b = i + 1; else segs.push({ a, b: i + 1, s: k });
        a = i + 1; n = 0;
      }
    }
  });
  return segs;
}

class Player {
  constructor(ui) {
    this.ui = ui; this.au = document.getElementById('au'); this.mem = new Map(); this.cached = new Set(); this.durs = new Map();
    this.cps = LS.get('sv:cps', 15); this.sleep = { mode: null, end: 0, iv: null }; this.ptok = 0; this.btok = 0; this.lastSave = 0;
    const au = this.au;
    au.addEventListener('timeupdate', () => this.onTime());
    au.addEventListener('ended', () => this.onEnded());
    au.addEventListener('error', () => this.onAudioError());
    au.addEventListener('pause', () => { if (this.playing && !this.waiting && this.mode === 'neural' && this.curData && !au.ended && !au.loop && !au.seeking) this.pause(); }); // paused by the OS / headset / a call
  }
  get mode() { return S.quality === 'basic' || !engine.supported ? 'basic' : 'neural'; }

  /* ----- load / geometry ----- */
  async load(meta, text, saved) {
    this.unload(); this.meta = meta; this.chunks = text.chunks; this.secs = text.secs; this.segs = makeSegs(text.chunks, text.secs);
    const cum = new Float64Array(this.chunks.length + 1); this.chunks.forEach((c, k) => cum[k + 1] = cum[k] + c[0].length);
    this.cum = cum; this.total = cum[cum.length - 1] || 1;
    this.i = Math.max(0, Math.min(saved.pct >= 99.5 ? 0 : (saved.i || 0), this.chunks.length - 1)); this.o = saved.pct >= 99.5 ? 0 : (saved.o || 0);
    this.cur = this.segOf(this.i); this.playing = false; this.waiting = false; this.done = false; this.prepSec = null; this.curData = null; this.fails = 0;
    await this.loadIndex(); this.bindMedia(); this.updateMedia();
  }
  async loadIndex() {
    this.cached.clear(); this.durs.clear();
    try { (await DB.audioIdx()).forEach(x => { if (x.bookId === this.meta.id && x.voice === S.nvoice && x.v === AV) { this.cached.add(x.k); this.durs.set(x.k, x.dur); } }); } catch {}
  }
  unload() {
    if (this.meta) this.pause(); this.setSleep(null);
    for (const d of this.mem.values()) URL.revokeObjectURL(d.url); this.mem.clear(); this.curData = null; this.meta = null;
  }
  secOf(i) { let lo = 0, hi = this.secs.length - 1; while (lo < hi) { const m = (lo + hi + 1) >> 1; if (this.secs[m].start <= i) lo = m; else hi = m - 1; } return lo; }
  segOf(i) { let lo = 0, hi = this.segs.length - 1; while (lo < hi) { const m = (lo + hi + 1) >> 1; if (this.segs[m].a <= i) lo = m; else hi = m - 1; } return lo; }
  setI(i) { this.i = i; this.cur = this.segOf(i); }
  pct() { return this.cum[this.i] / this.total * 100; }
  save(pct) { if (this.meta) { this.lastSave = Date.now(); LS.set('sv:p:' + this.meta.id, { i: this.i, o: +(this.o || 0).toFixed(1), pct: pct != null ? pct : this.pct(), sec: this.secs[this.secOf(this.i)].title, t: Date.now() }); } }
  key(k) { return `${this.meta.id}|${S.nvoice}|${AV}|${k}`; }

  /* ----- generation (neural) ----- */
  windowSegs() {
    const w = [];
    if (this.playing || this.waiting) for (let k = this.cur; k <= this.cur + AHEAD && k < this.segs.length; k++) w.push(k);
    if (this.prepSec != null) this.segs.forEach((s, k) => { if (s.s === this.prepSec) w.push(k); });
    return w;
  }
  has(k) { return this.mem.has(k) || this.cached.has(k); }
  genKick() { if (this.mode === 'neural' && this.meta) this.genLoop(); }
  async genLoop() {
    if (this.genBusy) return; this.genBusy = true; let finished = false;
    try {
      for (;;) {
        const k = this.windowSegs().find(x => !this.has(x)); if (k == null) { finished = true; break; }
        if (!(await this.generate(k))) break;
      }
      if (finished && this.prepSec != null) { this.prepSec = null; this.ui.toast('Chapter audio is ready to play offline.'); }
    } finally { this.genBusy = false; this.ui.onStatus(); }
  }
  async generate(k) {
    const seg = this.segs[k]; let ok = false;
    try { ok = await engine.ensure(); } catch {}
    if (!ok) { this.engineFailed(true); return false; }
    const t0 = performance.now(), parts = [], offs = []; let n = 0, chars = 0;
    for (let i = seg.a; i < seg.b; i++) {
      if (!this.windowSegs().includes(k)) return true; // listener moved away – abandon, loop picks the new target
      const [t, f] = this.chunks[i]; let r;
      for (let tries = 0; ; tries++) { try { r = await engine.generate(prepSpeech(t, f), S.nvoice); break; } catch { if (tries >= 1) { this.engineFailed(false); return false; } } }
      offs.push(n / SR); parts.push(r.pcm); n += r.pcm.length; chars += t.length;
      const nx = this.chunks[i + 1], pause = f === 2 ? 0.7 : (nx && nx[1] === 1 ? 0.4 : 0.12), gap = new Float32Array(Math.round(pause * SR)); parts.push(gap); n += gap.length;
    }
    const dur = n / SR; await this.store(k, encodeWav(concat(parts, n), SR), { offs, dur });
    this.rtf = dur / Math.max(0.05, (performance.now() - t0) / 1000);
    if (engine.kind !== 'mock') { this.cps = this.cps * 0.7 + (chars / Math.max(1, dur)) * 0.3; LS.set('sv:cps', this.cps); }
    this.ui.onStatus();
    if (this.playing && this.waiting && k === this.cur) this.playFrom(this.i, this.o);
    return true;
  }
  engineFailed(init) {
    this.pause();
    if (init) { S.quality = 'basic'; LS.set('sv:settings', S); this.ui.toast('The natural voice couldn’t start on this device, so SanaVerse switched to the Basic voice. You can retry in Settings.'); this.ui.onState(); }
    else this.ui.toast('Narration generation failed. Press Play to try again, or switch to the Basic voice in Settings.');
  }
  async store(k, blob, rec) {
    this.mem.set(k, { url: URL.createObjectURL(blob), offs: rec.offs, dur: rec.dur }); this.cached.add(k); this.durs.set(k, rec.dur);
    try { await DB.audioPut({ key: this.key(k), blob, offs: rec.offs, dur: rec.dur }, { key: this.key(k), bookId: this.meta.id, voice: S.nvoice, v: AV, k, size: blob.size, dur: rec.dur, t: Date.now() }); await this.trim(); }
    catch { if (!this.warned) { this.warned = 1; this.ui.toast('Not enough storage to keep generated audio. Playback still works, but audio may be regenerated.'); } }
  }
  async getSeg(k) {
    if (this.mem.has(k)) return this.mem.get(k);
    if (!this.cached.has(k)) return null;
    try { const r = await DB.audioGet(this.key(k)); if (r) { const d = { url: URL.createObjectURL(r.blob), offs: r.offs, dur: r.dur }; this.mem.set(k, d); return d; } } catch {}
    this.cached.delete(k); return null;
  }
  pruneMem() { for (const [k, d] of this.mem) if ((k < this.cur - 1 || k > this.cur + AHEAD + 1) && d !== this.curData) { URL.revokeObjectURL(d.url); this.mem.delete(k); } }
  async trim() { // keep the audio cache under the user's limit: other books first, then segments farthest from here
    const cap = S.cap * 1048576, idx = await DB.audioIdx(); let tot = idx.reduce((a, x) => a + x.size, 0); if (tot <= cap) return;
    const keep = new Set(this.windowSegs().map(k => this.key(k))), me = this.meta.id, c = this.cur;
    const cand = idx.filter(x => !keep.has(x.key)).sort((a, b) => ((a.bookId === me) - (b.bookId === me)) || (a.bookId === me ? Math.abs(b.k - c) - Math.abs(a.k - c) : a.t - b.t));
    const del = []; for (const x of cand) { if (tot <= cap * 0.9) break; tot -= x.size; del.push(x); }
    if (!del.length) return; await DB.audioDelete(del.map(x => x.key));
    del.filter(x => x.bookId === me && x.voice === S.nvoice).forEach(x => { this.cached.delete(x.k); this.durs.delete(x.k); const d = this.mem.get(x.k); if (d && d !== this.curData) { URL.revokeObjectURL(d.url); this.mem.delete(x.k); } });
  }
  async reloadVoice() { this.pause(); this.mem.forEach(d => URL.revokeObjectURL(d.url)); this.mem.clear(); this.curData = null; await this.loadIndex(); this.ui.onStatus(); }
  async clearAudio() { this.mem.forEach(d => d !== this.curData && URL.revokeObjectURL(d.url)); this.mem.clear(); this.cached.clear(); this.durs.clear(); await DB.audioClear().catch(() => {}); this.ui.onStatus(); }
  prepare() { this.prepSec = this.secOf(this.i); this.genKick(); this.ui.onStatus(); }
  ahead() {
    let s = this.curData ? Math.max(0, this.curData.dur - this.au.currentTime) : 0;
    for (let k = this.cur + 1; k < this.segs.length && this.has(k); k++) s += this.durs.get(k) || 0; return s;
  }

  /* ----- playback ----- */
  async play() {
    if (!this.meta) return;
    if (this.done) { this.setI(0); this.o = 0; this.done = false; }
    this.playing = true; this.fails = 0; this.ui.onState();
    if (this.mode === 'basic') return this.basicPlay();
    this.playFrom(this.i, this.o);
  }
  async playFrom(i, off = 0) {
    const tok = ++this.ptok; this.stopSpeech(); this.setI(i); this.o = off; const k = this.cur;
    this.waiting = true; this.genKick(); this.ui.onState();
    const d = await this.getSeg(k);
    if (tok !== this.ptok || !this.playing) return;
    if (!d) { this.setBuffering(); return; } // generate() calls playFrom again when this segment is ready
    this.waiting = false; this.curData = d; this.pruneMem(); this.genKick();
    const au = this.au, t = (d.offs[i - this.segs[k].a] || 0) + off;
    au.loop = false; au.src = d.url;
    au.onloadedmetadata = () => { au.onloadedmetadata = null; try { au.currentTime = Math.min(t, Math.max(0, au.duration - 0.2)); } catch {} au.playbackRate = S.rate; au.play().catch(e => this.playErr(e)); };
    au.preservesPitch = true; au.load(); this.ui.onState(); this.updateMedia(); this.ui.onChange();
  }
  setBuffering() { const au = this.au; this.curData = null; if (!au.loop || !au.src.endsWith(silenceUrl().slice(-12))) { au.src = silenceUrl(); au.loop = true; au.playbackRate = 1; au.play().catch(() => {}); } this.ui.onState(); }
  playErr(e) { if (e && e.name === 'AbortError') return; this.pause(); this.ui.toast(e && e.name === 'NotAllowedError' ? 'Tap Play to start the audio.' : 'The audio couldn’t be played. Press Play to try again.'); }
  onAudioError() { if (!this.playing || !this.curData || this.au.loop) return; const d = this.curData, k = this.cur; URL.revokeObjectURL(d.url); this.mem.delete(k); this.cached.delete(k);
    if (this.fails++ < 1) this.playFrom(this.i, this.o); else { this.pause(); this.ui.toast('This audio couldn’t be played. Press Play to regenerate it.'); } }
  pause() {
    if (!this.meta) return; this.playing = false; this.waiting = false; this.ptok++; this.btok++;
    try { this.au.pause(); this.au.loop = false; } catch {} this.stopSpeech(); this.save(); this.ui.onState(); this.mediaState();
  }
  onTime() {
    if (!this.playing || this.waiting || !this.curData || this.au.loop) return;
    const d = this.curData, seg = this.segs[this.cur], t = this.au.currentTime; let lo = 0, hi = d.offs.length - 1;
    while (lo < hi) { const m = (lo + hi + 1) >> 1; if (d.offs[m] <= t) lo = m; else hi = m - 1; }
    const i = seg.a + lo; this.o = Math.max(0, t - d.offs[lo]);
    if (i !== this.i) { this.i = i; this.ui.onChange(); this.save(); this.genKick(); } else if (Date.now() - this.lastSave > 3000) this.save();
    this.ui.onTick();
  }
  onEnded() {
    if (this.mode !== 'neural' || !this.playing || this.au.loop) return;
    const k = this.cur + 1;
    if (k >= this.segs.length) return this.finish();
    if (this.sleep.mode === 'sec' && this.segs[k].s !== this.segs[this.cur].s) { this.setI(this.segs[k].a); this.o = 0; this.pause(); this.setSleep(null); this.ui.onChange(); this.ui.toast('Sleep timer: paused at the end of the chapter.'); return; }
    this.fails = 0; this.playFrom(this.segs[k].a, 0);
  }
  finish() { this.playing = false; this.done = true; this.ptok++; this.save(100); this.ui.onState(); this.ui.onChange(); this.ui.toast('You’ve reached the end of the book.'); }
  jump(k, go) { k = Math.max(0, Math.min(this.chunks.length - 1, k)); this.done = false; this.setI(k); this.o = 0; this.fails = 0; this.ui.onChange(); this.save(); this.updateMedia(); if (go || this.playing) this.play(); }
  seek(sec) { // sec of narration (not book text): within the loaded segment if possible, otherwise by text length
    if (this.mode === 'neural' && this.curData && !this.waiting && this.au.duration) { const t = this.au.currentTime + sec; if (t >= 0 && t <= this.au.duration - 0.3) { this.au.currentTime = t; return; } }
    let need = Math.abs(sec) * this.cps, j = this.i;
    if (sec < 0) { while (j > 0 && need > 0) { j--; need -= this.chunks[j][0].length; } } else { while (j < this.chunks.length - 1 && need > 0) { need -= this.chunks[j][0].length; j++; } }
    this.jump(j);
  }
  prevSec() { const s = this.secOf(this.i); this.jump(this.i - this.secs[s].start > 3 || s === 0 ? this.secs[s].start : this.secs[s - 1].start); }
  nextSec() { const s = this.secOf(this.i); if (s + 1 < this.secs.length) this.jump(this.secs[s + 1].start); }
  setRate(r) { S.rate = r; this.au.playbackRate = r; if (this.playing && this.mode === 'basic') this.speak(); }

  /* ----- sleep timer ----- */
  setSleep(m) {
    clearInterval(this.sleep.iv); this.sleep.iv = null; this.sleep.mode = m;
    if (typeof m === 'number') { this.sleep.end = Date.now() + m * 60000; this.sleep.iv = setInterval(() => { if (this.sleep.end - Date.now() <= 0) { this.setSleep(null); this.pause(); this.ui.toast('Sleep timer finished.'); } else this.ui.onSleep(); }, 1000); }
    this.ui.onSleep();
  }

  /* ----- Media Session: lock screen, notification, headset buttons ----- */
  bindMedia() {
    if (this.mediaBound || !('mediaSession' in navigator)) return; this.mediaBound = true;
    const h = (n, f) => { try { navigator.mediaSession.setActionHandler(n, f); } catch {} };
    h('play', () => this.play()); h('pause', () => this.pause()); h('stop', () => this.pause());
    h('previoustrack', () => this.prevSec()); h('nexttrack', () => this.nextSec());
    h('seekbackward', () => this.seek(-15)); h('seekforward', () => this.seek(30));
  }
  updateMedia() {
    if (!('mediaSession' in navigator) || !this.meta || typeof MediaMetadata === 'undefined') return;
    try { navigator.mediaSession.metadata = new MediaMetadata({ title: this.secs[this.secOf(this.i)].title, artist: this.meta.title + (this.meta.author ? ' · ' + this.meta.author : ''), album: 'SanaVerse', artwork: [{ src: 'icon-512.png', sizes: '512x512', type: 'image/png' }] }); } catch {}
    this.mediaState();
  }
  mediaState() { if ('mediaSession' in navigator) try { navigator.mediaSession.playbackState = this.playing ? 'playing' : 'paused'; } catch {} }

  /* ----- Basic voice (device speech synthesis) ----- */
  basicPlay() {
    if (!('speechSynthesis' in window)) { this.playing = false; this.ui.onState(); return this.ui.toast('Your browser can’t read aloud. Try Chrome, Edge or Safari.'); }
    this.wake(); this.speak();
  }
  speak() {
    if (!this.playing) return;
    const tts = window.speechSynthesis, tok = ++this.btok; clearTimeout(this.wd);
    const [t, f] = this.chunks[this.i], u = new SpeechSynthesisUtterance(f === 2 ? t + '.' : t); u.rate = S.rate;
    const v = S.bvoice && tts.getVoices().find(x => x.voiceURI === S.bvoice); if (v) { u.voice = v; u.lang = v.lang; }
    let started = false;
    u.onstart = () => { started = true; this.fails = 0; clearTimeout(this.wd); };
    u.onend = () => { if (tok === this.btok) { clearTimeout(this.wd); this.advance(); } };
    u.onerror = e => { if (tok !== this.btok || e.error === 'canceled' || e.error === 'interrupted') return; this.retry(); };
    this.u = u; const need = tts.speaking || tts.pending; if (need) tts.cancel();
    const go = () => { if (tok === this.btok && this.playing) tts.speak(u); }; need ? setTimeout(go, 60) : go();
    this.wd = setTimeout(() => { if (!started && tok === this.btok) this.retry(); }, 7000);
  }
  retry() { if (++this.fails <= 2) return setTimeout(() => this.speak(), 300); this.pause(); this.ui.toast('Speech stopped. Check your device’s voice settings, then press Play.'); }
  advance() {
    const old = this.secOf(this.i);
    if (this.i >= this.chunks.length - 1) { this.unwake(); return this.finish(); }
    this.setI(this.i + 1); this.o = 0; this.ui.onChange(); this.save();
    if (this.sleep.mode === 'sec' && this.secOf(this.i) !== old) { this.pause(); this.setSleep(null); this.ui.toast('Sleep timer: paused at the end of the chapter.'); return; }
    this.speak();
  }
  stopSpeech() { clearTimeout(this.wd); this.btok++; try { window.speechSynthesis && window.speechSynthesis.cancel(); } catch {} this.unwake(); }
  async wake() { try { if ('wakeLock' in navigator && !this.wl) { this.wl = await navigator.wakeLock.request('screen'); this.wl.addEventListener('release', () => this.wl = null); } } catch {} }
  unwake() { try { this.wl && this.wl.release(); } catch {} this.wl = null; }
}


/* ===== app.js ===== */
/* SanaVerse – UI. Library, player, text view, settings. */




const $ = (s, r = document) => r.querySelector(s);
const h = (tag, cls, txt) => { const e = document.createElement(tag); if (cls) e.className = cls; if (txt != null) e.textContent = txt; return e; };
let toastT;
function toast(m) { const t = $('#toast'); t.textContent = m; t.classList.add('show'); clearTimeout(toastT); toastT = setTimeout(() => t.classList.remove('show'), 5000); }

let tab = 'listen', seeking = false, lastSec = -1, lastI = -1, lastStatus = 0, nativeDone = false;
const ui = { toast, onChange: () => upd(), onState: () => { renderPlay(); renderStatus(); }, onStatus: () => renderStatus(), onTick: () => { if (Date.now() - lastStatus > 1000) renderStatus(); }, onSleep: () => sleepUI() };
const P = new Player(ui);
window.SV = { P, S, engine, DB, LS }; // handy for debugging and automated tests

/* ---------- views ---------- */
function show(v) { $('#library').hidden = v !== 'library'; $('#book').hidden = v !== 'book'; document.body.classList.toggle('inbook', v === 'book'); window.scrollTo(0, 0); }
function busy(on, msg, pct) { $('#busy').hidden = !on; if (msg) $('#busyMsg').textContent = msg; $('#busyBar').style.width = (pct || 0) + '%'; }

/* ---------- import ---------- */
async function importFile(file) {
  if (!file) return;
  busy(true, 'Reading PDF…', 2);
  try {
    const { meta, text } = await extractPdf(file, (m, p) => busy(true, m, p));
    await DB.put(meta, text);
    navigator.storage && navigator.storage.persist && navigator.storage.persist().catch(() => {});
    busy(true, 'Ready to listen.', 100); busy(false); await openBook(meta.id);
  } catch (e) {
    busy(false);
    toast(e instanceof AppError ? e.message : (e && e.name === 'QuotaExceededError') ? 'Not enough storage space on this device for this book.' : 'Something went wrong reading this PDF. It may be damaged or unusual.');
    if (!(e instanceof AppError)) console.error(e);
  }
}

/* ---------- library ---------- */
function card(m, feat) {
  const d = h('article', 'card' + (feat ? ' feat' : '')), pc = m.p.pct || 0;
  if (feat) d.append(h('div', 'lbl', 'Continue Reading'));
  const head = h('div', 'head'), info = h('div');
  if (m.cover) { const im = h('img', 'cov'); im.src = m.cover; im.alt = ''; head.append(im); }
  info.append(h('h3', 'bt', m.title)); if (m.author) info.append(h('div', 'muted', m.author)); if (m.p.sec && pc > 0) info.append(h('div', 'muted small', m.p.sec));
  head.append(info); d.append(head);
  const bar = h('div', 'bar'), f = h('i'); f.style.width = pc + '%'; bar.append(f); bar.setAttribute('role', 'progressbar'); bar.setAttribute('aria-valuenow', Math.round(pc)); d.append(bar);
  d.append(h('div', 'muted small', Math.round(pc) + '% listened' + (pc >= 99.5 ? ' · Finished' : '') + ` · ${m.pages} pages`));
  const row = h('div', 'row');
  const go = h('button', 'btn primary', pc >= 99.5 ? 'Listen again' : pc > 0 ? 'Continue' : 'Listen'); go.onclick = () => openBook(m.id); row.append(go);
  if (!feat) {
    const rs = h('button', 'btn', 'Restart'); rs.onclick = () => { LS.set('sv:p:' + m.id, { i: 0, o: 0, pct: 0, t: Date.now() }); renderLibrary(); };
    const dl = h('button', 'btn danger', 'Delete'); dl.onclick = async () => { if (!confirm(`Delete “${m.title}” and its audio from this device?`)) return; await DB.del(m.id).catch(() => {}); ['p', 'b'].forEach(k => LS.del(`sv:${k}:${m.id}`)); renderLibrary(); };
    row.append(rs, dl);
  }
  d.append(row); return d;
}
async function renderLibrary() {
  let metas = [];
  try { metas = await DB.metas(); } catch { toast('Your library couldn’t be opened. Private browsing can block storage.'); }
  metas.forEach(m => m.p = LS.get('sv:p:' + m.id, { i: 0, pct: 0, t: 0 }));
  metas.sort((a, b) => (b.p.t || b.created) - (a.p.t || a.created));
  const cont = $('#continue'); cont.innerHTML = '';
  const last = metas.find(m => m.id === LS.get('sv:last') && m.p.pct > 0 && m.p.pct < 99.5); if (last) cont.append(card(last, true));
  const box = $('#books'); box.innerHTML = ''; metas.forEach(m => box.append(card(m)));
  $('#empty').hidden = metas.length > 0;
}
async function openBook(id) {
  if (P.meta) P.pause();
  let meta, text; try { meta = (await DB.metas()).find(m => m.id === id); text = await DB.text(id); } catch {}
  if (!meta || !text) return toast('This book couldn’t be opened. Try deleting it and adding it again.');
  await P.load(meta, text, LS.get('sv:p:' + id, { i: 0, pct: 0 })); LS.set('sv:last', id); lastSec = lastI = -1;
  $('#bTitle').textContent = meta.title; $('#q').value = ''; $('#results').hidden = true; $('#txt').hidden = false;
  show('book'); renderChapters(); renderMarks(); setTab('listen'); upd(); renderPlay(); renderStatus(); sleepUI(); renderChips();
}

/* ---------- player UI ---------- */
function upd() {
  if (!P.meta) return;
  const s = P.secOf(P.i), sp = P.cps * S.rate;
  $('#chap').textContent = P.secs[s].title; $('#bk').textContent = P.meta.title + (P.meta.author ? ' · ' + P.meta.author : '');
  $('#pct').textContent = Math.round(P.pct()) + '% of the book · chapter ' + (s + 1) + ' of ' + P.secs.length;
  $('#time').textContent = fmt(P.cum[P.i] / sp) + ' / ' + fmt(P.total / sp);
  const sl = $('#seek'); sl.max = P.chunks.length - 1; if (!seeking) sl.value = P.i;
  if (s !== lastSec) { lastSec = s; renderText(); markChapter(); P.updateMedia(); }
  if (P.i !== lastI) {
    lastI = P.i; const prev = $('#txt .cur'); if (prev) prev.classList.remove('cur');
    const c = $(`#txt [data-i="${P.i}"]`); if (c) { c.classList.add('cur'); if (tab === 'text' && !$('#txt').hidden) c.scrollIntoView({ block: 'center', behavior: 'smooth' }); }
  }
}
function renderPlay() {
  const b = $('#play'), on = P.meta && P.playing;
  b.innerHTML = on ? '<b>❚❚</b><small>Pause</small>' : '<b>▶</b><small>Play</small>'; b.setAttribute('aria-label', on ? 'Pause' : 'Play');
}
function statusText() {
  if (!P.meta) return '';
  if (P.mode === 'basic') return 'Basic device voice. It may stop when the screen turns off. Choose the Natural voice in Settings for background listening.';
  if (engine.state === 'downloading') return `Downloading natural voice… ${engine.mb.toFixed(0)} of ${engine.totalMb ? engine.totalMb.toFixed(0) : '~90'} MB. This happens once.`;
  if (engine.state === 'loading') return 'Loading natural voice…';
  if (engine.state === 'error') return 'The natural voice couldn’t start. Check your connection and press Play to try again.';
  let s = '';
  if (P.prepSec != null) { const ks = P.segs.map((x, k) => k).filter(k => P.segs[k].s === P.prepSec); s += `Preparing this chapter: ${ks.filter(k => P.has(k)).length} of ${ks.length} parts. `; }
  if (P.playing && P.waiting) return s + 'Preparing narration…';
  const a = P.ahead(); if (a > 1) s += `Audio ready ahead: ${fmt(a)}`;
  if (P.rtf) { s += (s ? ' · ' : '') + `voice speed ${P.rtf.toFixed(1)}× real time`; if (P.playing && P.rtf < S.rate * 1.05) s += '. Your device generates audio slower than it plays; try 1× speed or “Prepare this chapter”.'; }
  return s;
}
function renderStatus() { lastStatus = Date.now(); $('#audioStatus').textContent = statusText(); const pb = $('#prepBtn'); if (pb) pb.hidden = P.mode !== 'neural'; $('#prepHint').hidden = P.mode !== 'neural'; }
function renderText() {
  const box = $('#txt'); box.innerHTML = ''; box.style.fontSize = S.size + 'px';
  const s = P.secOf(P.i), a = P.secs[s].start, b = s + 1 < P.secs.length ? P.secs[s + 1].start : P.chunks.length; let p = null;
  for (let k = a; k < b; k++) { // textContent only: PDF text is never inserted as HTML
    const [t, f] = P.chunks[k];
    if (f === 2) { const e = h('h3', null, t); e.dataset.i = k; box.append(e); p = null; continue; }
    if (!p || f === 1) { p = h('p'); box.append(p); }
    const sp = h('span', 'ck', t + ' '); sp.dataset.i = k; p.append(sp);
  }
}
function markChapter() { document.querySelectorAll('#chapList .item').forEach((e, k) => e.classList.toggle('cur2', k === lastSec)); }
function renderChapters() {
  const box = $('#chapList'); box.innerHTML = '';
  P.secs.forEach(s => { const b = h('button', 'item'); b.append(h('div', null, s.title), h('div', 'mut', Math.round(P.cum[s.start] / P.total * 100) + '% into the book · ' + fmt(P.cum[s.start] / P.cps) + ' in')); b.onclick = () => { P.jump(s.start, true); setTab('listen'); }; box.append(b); });
}
function renderMarks() {
  const box = $('#markList'); box.innerHTML = ''; const L = LS.get('sv:b:' + P.meta.id, []);
  if (!L.length) { box.append(h('p', 'muted', 'No bookmarks yet. Tap “Bookmark this spot” on the Listen tab.')); return; }
  L.sort((a, b) => a.i - b.i).forEach(m => {
    const r = h('div', 'mk'), b = h('button', 'item'); b.append(h('div', null, '🔖 ' + m.sec), h('div', 'mut', m.at));
    b.onclick = () => { P.jump(m.i, true); setTab('listen'); };
    const x = h('button', 'btn', 'Remove'); x.setAttribute('aria-label', 'Remove bookmark at ' + m.at);
    x.onclick = () => { LS.set('sv:b:' + P.meta.id, LS.get('sv:b:' + P.meta.id, []).filter(z => z.t !== m.t)); renderMarks(); };
    r.append(b, x); box.append(r);
  });
}
function setTab(t) {
  tab = t; document.querySelectorAll('.tabs button').forEach(b => b.setAttribute('aria-selected', b.dataset.tab === t));
  ['listen', 'text', 'chapters', 'marks'].forEach(n => $('#tab-' + n).hidden = n !== t);
  if (t === 'text') { const c = $('#txt .cur'); if (c) c.scrollIntoView({ block: 'center' }); }
  if (t === 'marks') renderMarks();
}
function renderChips() {
  const sp = $('#speeds'); sp.innerHTML = '';
  [0.75, 1, 1.25, 1.5, 1.75, 2].forEach(r => { const b = h('button', null, r + '×'); b.setAttribute('aria-pressed', S.rate === r); b.onclick = () => { P.setRate(r); saveS(); renderChips(); upd(); renderStatus(); }; sp.append(b); });
  const sl = $('#sleeps'); sl.innerHTML = '';
  [[15, '15 min'], [30, '30 min'], [45, '45 min'], [60, '60 min'], ['sec', 'End of chapter'], [null, 'Off']].forEach(([m, l]) => { const b = h('button', null, l); b.setAttribute('aria-pressed', P.sleep.mode === m); b.onclick = () => { P.setSleep(m); renderChips(); }; sl.append(b); });
}
function sleepUI() { const sl = P.sleep; $('#sleepInfo').textContent = sl.mode === 'sec' ? 'Will pause at the end of this chapter.' : typeof sl.mode === 'number' ? 'Pausing in ' + fmt((sl.end - Date.now()) / 1000) : ''; if (!sl.mode) renderChips(); }
function addMark() { const L = LS.get('sv:b:' + P.meta.id, []), at = fmt(P.cum[P.i] / P.cps); L.push({ i: P.i, sec: P.secs[P.secOf(P.i)].title, at, t: Date.now() }); LS.set('sv:b:' + P.meta.id, L); renderMarks(); toast('Bookmarked at ' + at); }
function doSearch() {
  const q = $('#q').value.trim().toLowerCase(), box = $('#results'); box.innerHTML = ''; box.hidden = !q; $('#txt').hidden = !!q; if (!P.meta || !q) return;
  if (q.length < 2) { box.append(h('p', 'muted', 'Keep typing…')); return; }
  let n = 0;
  for (let k = 0; k < P.chunks.length && n < 50; k++) {
    const t = P.chunks[k][0], x = t.toLowerCase().indexOf(q); if (x < 0) continue; n++;
    const b = h('button', 'res'); b.append(h('span', 'rs', P.secs[P.secOf(k)].title), h('span', null, '…' + t.slice(Math.max(0, x - 40), x + q.length + 60) + '…'));
    b.onclick = () => { $('#q').value = ''; doSearch(); P.jump(k, true); }; box.append(b);
  }
  if (!n) box.append(h('p', 'muted', 'No matches found.'));
}

/* ---------- play / voice setup ---------- */
async function nativePrep() { if (nativeDone) return; nativeDone = true; try { await Promise.race([window.SVNative && window.SVNative.prepare && window.SVNative.prepare(), new Promise(r => setTimeout(r, 1500))]); } catch {} }
async function togglePlay() {
  if (!P.meta) return;
  if (P.playing) return P.pause();
  if (P.mode === 'neural' && !engine.ready && !engine.modelKnown) return openSetup();
  await nativePrep(); P.play();
}
function setupUI() {
  const e = engine, pct = e.totalMb ? Math.min(100, e.mb / e.totalMb * 100) : 0;
  $('#setupBar').style.width = pct + '%';
  $('#setupMsg').textContent = e.state === 'downloading' ? `Downloading… ${e.mb.toFixed(0)} of ${e.totalMb ? e.totalMb.toFixed(0) : '~90'} MB` : e.state === 'loading' ? 'Starting the voice…' : e.state === 'error' ? 'Download failed. Check your connection and try again.' : '';
}
function openSetup() { setupUI(); $('#setupGo').disabled = false; $('#setup').showModal(); }
engine.on(() => { renderStatus(); if ($('#setup').open) setupUI(); });

/* ---------- settings ---------- */
function applyTheme() { S.theme === 'auto' ? document.documentElement.removeAttribute('data-theme') : document.documentElement.dataset.theme = S.theme; }
function fillVoices() {
  const nv = $('#setNVoice'); if (!nv.options.length) VOICES.forEach(([v, l]) => nv.append(new Option(l, v))); nv.value = S.nvoice;
  if (!('speechSynthesis' in window)) return;
  const sel = $('#setBVoice'), vs = speechSynthesis.getVoices(), lang = (navigator.language || 'en').slice(0, 2);
  sel.innerHTML = ''; sel.append(new Option('Device default', ''));
  [...vs].sort((a, b) => (b.lang.startsWith(lang) - a.lang.startsWith(lang)) || a.name.localeCompare(b.name)).forEach(v => sel.append(new Option(`${v.name} (${v.lang})`, v.voiceURI))); sel.value = S.bvoice;
}
async function openSettings() {
  $('#setQuality').value = S.quality; $('#setTheme').value = S.theme; $('#setSize').value = S.size; $('#sizeVal').textContent = S.size + 'px'; $('#setCap').value = String(S.cap); fillVoices();
  $('#settings').showModal();
  let a = 0; try { a = (await DB.audioIdx()).reduce((x, y) => x + y.size, 0); } catch {}
  let u = ''; try { const e = await navigator.storage.estimate(); u = ` Total storage used: ${(e.usage / 1048576).toFixed(0)} MB.`; } catch {}
  $('#storeInfo').textContent = `Generated audio: ${(a / 1048576).toFixed(0)} MB. Natural voice: ${engine.modelKnown ? 'downloaded' : 'not downloaded yet'}.${u}`;
}
function bind() {
  $('#file').addEventListener('change', e => { importFile(e.target.files[0]); e.target.value = ''; });
  document.addEventListener('dragover', e => e.preventDefault());
  document.addEventListener('drop', e => { e.preventDefault(); if (!$('#library').hidden) importFile(e.dataTransfer.files[0]); });
  document.querySelectorAll('.openSettings').forEach(b => b.onclick = openSettings);
  $('#closeSettings').onclick = () => $('#settings').close();
  $('#setTheme').onchange = e => { S.theme = e.target.value; saveS(); applyTheme(); };
  $('#setQuality').onchange = e => { if (P.meta) P.pause(); S.quality = e.target.value; saveS(); renderStatus(); renderPlay(); };
  $('#setNVoice').onchange = async e => { S.nvoice = e.target.value; saveS(); if (P.meta) await P.reloadVoice(); };
  $('#setBVoice').onchange = e => { S.bvoice = e.target.value; saveS(); if (P.playing && P.mode === 'basic') P.speak(); };
  $('#setCap').onchange = e => { S.cap = +e.target.value; saveS(); };
  $('#setSize').oninput = e => { S.size = +e.target.value; saveS(); $('#sizeVal').textContent = S.size + 'px'; $('#txt').style.fontSize = S.size + 'px'; };
  $('#clearAudio').onclick = async () => { if (P.meta) P.pause(); await P.clearAudio(); toast('Generated audio cleared.'); openSettings(); };
  $('#removeModel').onclick = async () => { if (!confirm('Remove the downloaded voice model? It will need to be downloaded again (about 90 MB) before the Natural voice can be used.')) return; if (P.meta) P.pause(); await engine.removeModel(); toast('Voice model removed.'); openSettings(); };
  $('#clearAll').onclick = async () => {
    if (!confirm('Delete every book, bookmark, progress record and generated audio from this device?')) return;
    P.unload(); await DB.clear().catch(() => {});
    Object.keys(localStorage).filter(k => /^sv:(p|b|last)/.test(k)).forEach(k => LS.del(k));
    $('#settings').close(); show('library'); renderLibrary(); toast('All local data deleted.');
  };
  $('#setupGo').onclick = async () => { $('#setupGo').disabled = true; const ok = await engine.ensure(); if (ok) { $('#setup').close(); await nativePrep(); P.play(); } else { setupUI(); $('#setupGo').disabled = false; } };
  $('#setupBasic').onclick = () => { S.quality = 'basic'; saveS(); $('#setup').close(); renderStatus(); P.play(); };
  $('#setupCancel').onclick = () => $('#setup').close();
  $('#back').onclick = () => { P.pause(); show('library'); renderLibrary(); };
  document.querySelectorAll('.tabs button').forEach(b => b.onclick = () => setTab(b.dataset.tab));
  $('#play').onclick = togglePlay;
  $('#back15').onclick = () => P.meta && P.seek(-15); $('#fwd30').onclick = () => P.meta && P.seek(30);
  $('#prev').onclick = () => P.meta && P.prevSec(); $('#next').onclick = () => P.meta && P.nextSec();
  const sl = $('#seek');
  sl.addEventListener('input', () => { seeking = true; if (P.meta) $('#time').textContent = fmt(P.cum[+sl.value] / (P.cps * S.rate)) + ' / ' + fmt(P.total / (P.cps * S.rate)); });
  sl.addEventListener('change', () => { seeking = false; if (P.meta) P.jump(+sl.value); });
  $('#markBtn').onclick = () => P.meta && addMark();
  $('#prepBtn').onclick = async () => { if (!P.meta) return; if (!engine.ready && !engine.modelKnown) return openSetup(); P.prepare(); toast('Preparing this chapter’s audio. You can keep this screen open or come back later.'); };
  $('#restartBtn').onclick = () => { if (P.meta && confirm('Restart this book from the beginning?')) { P.pause(); P.jump(0, true); } };
  $('#txt').onclick = e => { const c = e.target.closest('[data-i]'); if (c && P.meta) P.jump(+c.dataset.i, true); };
  let sT; $('#q').addEventListener('input', () => { clearTimeout(sT); sT = setTimeout(doSearch, 250); });
  document.addEventListener('keydown', e => {
    if (!P.meta || $('#book').hidden || e.target !== document.body) return;
    if (e.code === 'Space') { e.preventDefault(); togglePlay(); } else if (e.key === 'ArrowLeft') P.seek(-15); else if (e.key === 'ArrowRight') P.seek(30);
  });
  document.addEventListener('visibilitychange', () => {
    if (P.meta) P.save();
    if (document.visibilityState === 'visible' && P.meta && P.playing) { if (P.mode === 'basic') { P.wake(); if (!speechSynthesis.speaking && !speechSynthesis.pending) P.speak(); } renderStatus(); upd(); }
  });
  window.addEventListener('pagehide', () => P.meta && P.save());
  if ('speechSynthesis' in window) speechSynthesis.onvoiceschanged = fillVoices;
}
(function init() {
  applyTheme(); bind(); renderChips();
  if (!('indexedDB' in window)) toast('This browser can’t store books locally, so SanaVerse won’t work here.');
  if ('serviceWorker' in navigator && location.protocol !== 'file:') navigator.serviceWorker.register('sw.js').catch(() => {});
  renderLibrary();
})();


})();
